#!/bin/fish

function validate_mount_points
  grep -qs '/mnt/backup ' /proc/mounts && grep -qs '/mnt/snapshots/home ' /proc/mounts
end

validate_mount_points
set validate_mount_status $status


if not test $validate_mount_status -eq 0
  echo "Mount points doesn't exist."
  exit $validate_mount_status
end

yinvent -t
if not test $status -eq 0
  echo "No time for backups"
  exit 1
end

set level (yinvent -n)
set mlabel (yinvent -m)
set path (yinvent -p)

mkdir -p $path
xfsdump -e -l $level -L "home.$mlabel.$level" -M "home.$mlabel" -f $path/home.$level.xfs /mnt/snapshots/home

