#!/bin/fish

function validate_mount_points
  grep -qs '/mnt/backup ' /proc/mounts && grep -qs '/mnt/snapshots/home ' /proc/mounts
end

validate_mount_points
set validate_mount_status $status


if not test $validate_mount_status -eq 0
  echo "Mount points doesn't exist."
  exit $validate_mount_status
end

set level (yinvent -n)
echo $level

xfsdump -e -l $level -L "yesterday.daily.session.$level" -M "sda1" -f /mnt/backup/yesterday/daily/day.$level/home.xfs /mnt/snapshots/home

