#!/bin/sh

config() {
  [ -r $XDG_CONFIG_HOME/yesterday/conf ] && . $XDG_CONFIG_HOME/yesterday/conf
}

validate_config() {
  [ -n "$__SOURCE" -a -n "$__DEST" ]
}

name_of_prev() {
  [ -L "$1/__prev" ] && readlink "$1/__prev"
}

do_backup() {
  echo "Starting daily backup: $1 -> $2/$3"
  mkdir -p $2
  if [ -d "$2/__prev/" ]
  then
    rsync -aR --delete --link-dest="$2/__prev/" $1 "$2/$3"
  else
    rsync -aR                                   $1 "$2/$3"
  fi
  rm -f "$2/__prev"
  ln -s "$3" "$2/__prev"
}

config
validate_config
validate_config_status=$?

if ! $(exit $validate_config_status)
then
  echo "Looks like your configuration is misleading. Visit https://github.com/mbauhardt/yesterday for details."
  exit $validate_config_status
fi


__DAILY__DEST="$__DEST/daily"
__DAILY__LABEL=$(date +%A)
__DAILY__PREV__RUN=$(name_of_prev "$__DAILY__DEST")

if [ "$__DAILY__LABEL" != "$__DAILY__PREV__RUN" ]
then
  do_backup "$__SOURCE" "$__DAILY__DEST" "$__DAILY__LABEL"
else
  echo "Skipping daily backup."
fi

