#!/bin/fish

function count_level
  xfsdump -I depth=2,mobjlabel=home.(current_label),mnt="void:/mnt/snapshots/home" | grep "level:" | wc -l
end

function current_level
  if test (count_level) -gt 0
    xfsdump -I depth=2,mobjlabel=home.(current_label),mnt="void:/mnt/snapshots/home" | grep "level:" | tail -n1 | awk '{ print $2 }'
  else
    false
    return
  end
end

function next_level
  if test (count_level) -gt 0
    current_level | awk '{ print $1 < 9 ? $1 + 1 : 0 }'
  else
    echo 0
  end
end

function last_dump_in_days
  if test (count_level) -gt 0
    set last_run (xfsdump -I depth=2,mobjlabel=home.(current_label),mnt="void:/mnt/snapshots/home" | grep "time:" | tail -n1 | awk -F"time:" '{print $2}' | xargs)
    set diff_in_sec (math (date --date="(date)" +%s) - (date --date="$last_run" +%s))
    math $diff_in_sec / 86400
  else
    false
    return
  end
end

function current_label
  date +%b
end

function time_for_dump
  if test (count_level) -gt 0
    current_level -lt 9 -a last_dump_in_days -gt 2
    return
  else
    true
    return
  end
end

function dump_path
  echo "/mnt/backup/yesterday/"(current_label)
end

function print_usage
  echo "Usage"
end

if test (count $argv) -eq 0
  print_usage
  exit 0
end

argparse --name=yinvent 'h/help' 'c/count' 'l/level' 'n/next' 'm/medialabel' 'd/days' 't/time' 'p/path' -- $argv
if not test $status -eq 0
  exit 1
end


if test (count $_flag_h) -eq 1
  print_usage
else if test (count $_flag_c) -eq 1
  count_level
else if test (count $_flag_l) -eq 1
  current_level
else if test (count $_flag_n) -eq 1
  next_level
else if test (count $_flag_m) -eq 1
  current_label
else if test (count $_flag_d) -eq 1
  last_dump_in_days
else if test (count $_flag_t) -eq 1
  time_for_dump
  exit $status
else if test (count $_flag_p) -eq 1
  dump_path
end

