#!/bin/sh

current_level() {
  xfsdump -I depth=2,mobjlabel="sda",mnt="void:/mnt/snapshot" | grep "level:" | tail -n1 | awk '{ print $2 }'
}

next_level() {
  level=$(current_level)
  if [ -n "$level" ]
  then
    echo $level | awk '{ print $1 < 9 ? $1 + 1 : 0 }'
  else
    echo 0
  fi
}

last_dump_in_days() {
  local last_run=$(xfsdump -I depth=2,mobjlabel="sda",mnt="void:/mnt/snapshot" | grep "time:" | tail -n1 | awk -F"time:" '{print $2}' | xargs)
  local diff_in_sec=$(expr $(date --date="$(date)" +%s) - $(date --date="$last_run" +%s))
  expr $diff_in_sec / 86400
}

time_for_dump() {
  [ $(last_dump_in_days) -gt 1 ]
}

time_for_dump

